### ISSUE TITLE
todo list for site-adjust and district stuff

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ffh-packages#1]
- [x] announce district via respondd in ```ffh-district-core```
- [ ] maybe validating the district name should be done by ```ffh-district-core```?
- [x] dependencies between packages
- [x] execute everything in ```/lib/gluon/district-change.d/*``` instead of ```/lib/gluon/site-adjust```?
- [x] move ```/lib/gluon/site-adjust``` to ```/lib/gluon/district-change.d/site-adjust```
- [x] update documentation in READMEs
- [x] comment [here](https://github.com/freifunk-gluon/gluon/pull/1003) about our packages (this should be done after documentation is finished)
- [x] evaluate `ip link show br-setup` instead of running telnetd
---
**v2**
- [ ] move ```districts.lua``` to site repo?

**Comment by lemoer** [comment]
## test cases

To update the routers without config changes, flash with: `sysupgrade -n`

**different scenarios:**
- upgrade from actual firmware
    1. to intermediate with districts
    2. to final with different sites
- new firmware with intermediate
    1. upgrade to different sites
- new firmware with final version

**tests which only need to be done in one version:**
- is i18n working correctly in config mode?

**tests in each step:**
- does changing the district work in each state?
- is the district correctly announced by respondd?

**tests in intermediate:**
- is the server asked properly every hour?
- are multiple (remote) changes of the district working?

**tests in final:**
- do the routers mesh correctly?
- can they connect to the gateways?
- can we send packets across the different l2 networks?

**tests in config mode:**
- ensure especially that `ffh-district-site-adjust` doesn't reboot when we submit the luci form

**Comment by lemoer** [comment]
## potential issue

There is one issue left, which could lead to a bad situation.

1. both `ffh-district-site-adjust` and `ffh-district-migrate` are installed
2. `ffh-district-migrate` will ask the webserver every hour for a new district value
3. webserver says, the node should migrate too `mittw` (notice the typo. it should correctly be `mitte`)
4. `ffh-district-migrate` will set the uci district value to `mittw`
5. then it calls the routines `ffh-district-site-adjust`, especially this [case](https://github.com/freifunkh/ffh-packages/blob/master/ffh-district-site-adjust/files/lib/gluon/upgrade/002-adjust-site-config#L27). So `ffh-district-site-adjust` will override the uci value to `leetfeld`, because `mittw` is no valid district, since it's not defined in the [districts.lua](https://github.com/freifunkh/ffh-packages/blob/master/ffh-district-core/files/usr/lib/lua/gluon/districts.lua).
6. in the next hour, we again beginn at step 2

So all in all, this would lead to a situation, where the router would write to it's flash every hour. What do you think about this @1977er @AiyionPrime ?

**Comment by AiyionPrime** [comment]
For everyone else:
We just discussed the matter and came to the conclusion not to write the district leetfeld to flash, ever.
Leetfeld/null is returned though, if respondd asks

**Comment by lemoer** [comment]
No longer relevant...
